scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: 
    - 'localhost:9090'
remote_write:
- url: "http://prometheus-mongodb-adapter:8080/write"
remote_read:
- url: "http://prometheus-mongodb-adapter:8080/read"
